# Generated by Django 3.0.6 on 2020-05-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0028_cascade_clipboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascadeclipboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
    ]
